In [7]:
import pandas as pd
import numpy as np

from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [9]:
vic_data = pd.read_csv('../../data/victoria.csv', parse_dates=[0])

In [10]:
vic_data

,Time (UTC+10),Regions VIC Trading Price ($/MWh),Regions VIC Trading Total Intermittent Generation (MW),Regions VIC Operational Demand (MW),Time,Hour,Day
0,2018-01-01 00:00:00,90.43,146.87,4599,00:00:00,0,1
1,2018-01-01 00:30:00,92.46,131.68,4398,00:30:00,0,1
2,2018-01-01 01:00:00,87.62,119.98,4238,01:00:00,1,1
3,2018-01-01 01:30:00,73.08,123.86,4112,01:30:00,1,1
4,2018-01-01 02:00:00,70.18,132.72,3956,02:00:00,2,1
...,...,...,...,...,...,...,...
63452,2021-08-14 22:00:00,49.93,182.52,5492,22:00:00,22,6
63453,2021-08-14 22:30:00,62.86,206.23,5344,22:30:00,22,6
63454,2021-08-14 23:00:00,32.26,215.20,5204,23:00:00,23,6
63455,2021-08-14 23:30:00,25.10,226.95,5268,23:30:00,23,6
63456,2021-08-15 00:00:00,8.73,251.75,5244,00:00:00,0,7

In [3]:
# drop the index column

# vic_data = vic_data.drop(vic_data.columns[0], axis=1)

In [11]:
vic_data.to_csv('../../data/victoria.csv', index=False)

In [17]:
vic_training = vic_data.loc[(vic_data['Time (UTC+10)'] >= '2018-01-01') &
                            (vic_data['Time (UTC+10)'] < '2021-01-01')]

In [18]:
vic_training

,Time (UTC+10),Regions VIC Trading Price ($/MWh),Regions VIC Trading Total Intermittent Generation (MW),Regions VIC Operational Demand (MW),Time,Hour,Day
0,2018-01-01 00:00:00,90.43,146.87,4599,00:00:00,0,1
1,2018-01-01 00:30:00,92.46,131.68,4398,00:30:00,0,1
2,2018-01-01 01:00:00,87.62,119.98,4238,01:00:00,1,1
3,2018-01-01 01:30:00,73.08,123.86,4112,01:30:00,1,1
4,2018-01-01 02:00:00,70.18,132.72,3956,02:00:00,2,1
...,...,...,...,...,...,...,...
52603,2020-12-31 21:30:00,35.05,295.14,4421,21:30:00,21,4
52604,2020-12-31 22:00:00,35.49,272.81,4353,22:00:00,22,4
52605,2020-12-31 22:30:00,48.25,221.45,4323,22:30:00,22,4
52606,2020-12-31 23:00:00,38.66,189.40,4330,23:00:00,23,4
52607,2020-12-31 23:30:00,50.15,185.52,4526,23:30:00,23,4

In [19]:
vic_validation = vic_data.loc[(vic_data['Time (UTC+10)'] > '2021-01-01') &
                           (vic_data['Time (UTC+10)'] < '2021-07-01')]

In [20]:
vic_validation

,Time (UTC+10),Regions VIC Trading Price ($/MWh),Regions VIC Trading Total Intermittent Generation (MW),Regions VIC Operational Demand (MW),Time,Hour,Day
52608,2021-01-01 00:00:00,43.48,207.49,4555,00:00:00,0,5
52609,2021-01-01 00:30:00,37.21,208.82,4396,00:30:00,0,5
52610,2021-01-01 01:00:00,36.37,192.02,4252,01:00:00,1,5
52611,2021-01-01 01:30:00,25.02,172.57,4137,01:30:00,1,5
52612,2021-01-01 02:00:00,14.60,167.15,3976,02:00:00,2,5
...,...,...,...,...,...,...,...
61291,2021-06-30 21:30:00,65.79,205.28,6082,21:30:00,21,3
61292,2021-06-30 22:00:00,92.52,216.45,5874,22:00:00,22,3
61293,2021-06-30 22:30:00,67.46,224.00,5653,22:30:00,22,3
61294,2021-06-30 23:00:00,60.16,211.81,5397,23:00:00,23,3
61295,2021-06-30 23:30:00,73.85,190.95,5487,23:30:00,23,3

In [12]:
vic_testing = vic_data.loc[(vic_data['Time (UTC+10)'] >= '2021-07-01') & (vic_data['Time (UTC+10)'] < '2021-08-12')]

In [13]:
vic_testing

,Time (UTC+10),Regions VIC Trading Price ($/MWh),Regions VIC Trading Total Intermittent Generation (MW),Regions VIC Operational Demand (MW),Time,Hour,Day
61296,2021-07-01 00:00:00,51.71,184.60,5410,00:00:00,0,4
61297,2021-07-01 00:30:00,90.51,175.53,5192,00:30:00,0,4
61298,2021-07-01 01:00:00,73.91,130.56,5016,01:00:00,1,4
61299,2021-07-01 01:30:00,33.79,120.55,4837,01:30:00,1,4
61300,2021-07-01 02:00:00,43.57,125.84,4661,02:00:00,2,4
...,...,...,...,...,...,...,...
63307,2021-08-11 21:30:00,61.52,304.83,5911,21:30:00,21,3
63308,2021-08-11 22:00:00,43.00,321.83,5695,22:00:00,22,3
63309,2021-08-11 22:30:00,54.29,330.72,5450,22:30:00,22,3
63310,2021-08-11 23:00:00,49.25,320.81,5269,23:00:00,23,3
63311,2021-08-11 23:30:00,51.37,296.36,5332,23:30:00,23,3

Saving the csv files into `data` directory.

In [23]:
vic_training.to_csv('../../data/training.csv', index=False)
vic_validation.to_csv('../../data/validation.csv', index=False)
vic_testing.to_csv('../../data/testing.csv', index=False)

In [14]:
bonus_data = pd.read_excel('../../data/market_data.xlsx', parse_dates=[0])

In [17]:
bonus_data = bonus_data.drop(['Regions NSW Trading Price ($/MWh)', 'Regions SA Trading Price ($/MWh)', 
                              'Regions TAS Trading Price ($/MWh)', 'Regions VIC Trading Price ($/MWh)'], axis = 1)
bonus_data

,Time (UTC+10),Regions NSW Trading Total Intermittent Generation (MW),Regions SA Trading Total Intermittent Generation (MW),Regions TAS Trading Total Intermittent Generation (MW),Regions VIC Trading Total Intermittent Generation (MW),Regions NSW Operational Demand (MW),Regions SA Operational Demand (MW),Regions TAS Operational Demand (MW),Regions VIC Operational Demand (MW)
0,2018-01-01 00:00:00,0.18,60.53,121.68,146.87,7100,1398,1091,4599
1,2018-01-01 00:30:00,0.15,43.07,118.73,131.68,6974,1359,1082,4398
2,2018-01-01 01:00:00,0.13,41.67,110.48,119.98,6790,1316,1071,4238
3,2018-01-01 01:30:00,0.14,42.15,120.09,123.86,6536,1240,1067,4112
4,2018-01-01 02:00:00,0.16,38.31,114.64,132.72,6339,1194,1061,3956
...,...,...,...,...,...,...,...,...,...
63452,2021-08-14 22:00:00,8.74,36.42,154.69,182.52,8491,1718,1255,5492
63453,2021-08-14 22:30:00,7.52,51.83,156.09,206.23,8376,1665,1244,5344
63454,2021-08-14 23:00:00,7.69,42.04,160.30,215.20,8194,1614,1207,5204
63455,2021-08-14 23:30:00,8.35,38.04,167.00,226.95,8022,1573,1163,5268
63456,2021-08-15 00:00:00,8.07,47.47,156.92,251.75,7867,1680,1139,5244

In [18]:
bonus_training = bonus_data.loc[(bonus_data['Time (UTC+10)'] >= '2018-01-01') &
                            (bonus_data['Time (UTC+10)'] < '2021-01-01')]

In [20]:
bonus_validation = bonus_data.loc[(bonus_data['Time (UTC+10)'] > '2021-01-01') &
                           (bonus_data['Time (UTC+10)'] < '2021-07-01')]

In [21]:
bonus_testing = bonus_data.loc[(bonus_data['Time (UTC+10)'] >= '2021-07-01') & 
                               (bonus_data['Time (UTC+10)'] < '2021-08-12')]

In [22]:
bonus_training.to_csv('../../data/bonus_training.csv', index=False)
bonus_validation.to_csv('../../data/bonus_validation.csv', index=False)
bonus_testing.to_csv('../../data/bonus_testing.csv', index=False)